// <auto-generated />
namespace IdentityDEMO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedShippingField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedShippingField));
        
        string IMigrationMetadata.Id
        {
            get { return "202202080902162_AddedShippingField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
